postgres:
  build: ./postgres/
  environment: 
    POSTGRES_USER: apiman
    POSTGRES_PASSWORD: apiman_p123 
  ports:
    - 5432:5432    
services:
  build: ./services/
  ports:
    - 8081:8080
    - 9991:9990 
apiman:
  build: ./apiman/
  links:
    - postgres:postgresserver
    - services:services
  ports:
    - 8080:8080
    - 9990:9990
